Labsland ready
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch main
# Your branch is up to date with 'origin/main'.
#
# Changes to be committed:
#	modified:   lab1/db/lab_general.db_info
#	modified:   lab1/lab_general.qws
#	modified:   lab2/DE1_SoC.sv
#	new file:   lab2/Launch_ModelSim.bat
#	new file:   lab2/c5_pin_model_dump.txt
#	new file:   lab2/db/.cmp.kpt
#	new file:   lab2/db/alt_u_div_mse.tdf
#	new file:   lab2/db/altsyncram_1g12.tdf
#	new file:   lab2/db/altsyncram_s6o1.tdf
#	new file:   lab2/db/lab_general.(0).cnf.cdb
#	new file:   lab2/db/lab_general.(0).cnf.hdb
#	new file:   lab2/db/lab_general.(1).cnf.cdb
#	new file:   lab2/db/lab_general.(1).cnf.hdb
#	new file:   lab2/db/lab_general.(10).cnf.cdb
#	new file:   lab2/db/lab_general.(10).cnf.hdb
#	new file:   lab2/db/lab_general.(11).cnf.cdb
#	new file:   lab2/db/lab_general.(11).cnf.hdb
#	new file:   lab2/db/lab_general.(12).cnf.cdb
#	new file:   lab2/db/lab_general.(12).cnf.hdb
#	new file:   lab2/db/lab_general.(13).cnf.cdb
#	new file:   lab2/db/lab_general.(13).cnf.hdb
#	new file:   lab2/db/lab_general.(14).cnf.cdb
#	new file:   lab2/db/lab_general.(14).cnf.hdb
#	new file:   lab2/db/lab_general.(15).cnf.cdb
#	new file:   lab2/db/lab_general.(15).cnf.hdb
#	new file:   lab2/db/lab_general.(2).cnf.cdb
#	new file:   lab2/db/lab_general.(2).cnf.hdb
#	new file:   lab2/db/lab_general.(3).cnf.cdb
#	new file:   lab2/db/lab_general.(3).cnf.hdb
#	new file:   lab2/db/lab_general.(4).cnf.cdb
#	new file:   lab2/db/lab_general.(4).cnf.hdb
#	new file:   lab2/db/lab_general.(5).cnf.cdb
#	new file:   lab2/db/lab_general.(5).cnf.hdb
#	new file:   lab2/db/lab_general.(6).cnf.cdb
#	new file:   lab2/db/lab_general.(6).cnf.hdb
#	new file:   lab2/db/lab_general.(7).cnf.cdb
#	new file:   lab2/db/lab_general.(7).cnf.hdb
#	new file:   lab2/db/lab_general.(8).cnf.cdb
#	new file:   lab2/db/lab_general.(8).cnf.hdb
#	new file:   lab2/db/lab_general.(9).cnf.cdb
#	new file:   lab2/db/lab_general.(9).cnf.hdb
#	new file:   lab2/db/lab_general.ae.hdb
#	new file:   lab2/db/lab_general.asm.qmsg
#	new file:   lab2/db/lab_general.asm.rdb
#	new file:   lab2/db/lab_general.cbx.xml
#	new file:   lab2/db/lab_general.cmp.bpm
#	new file:   lab2/db/lab_general.cmp.cdb
#	new file:   lab2/db/lab_general.cmp.hdb
#	new file:   lab2/db/lab_general.cmp.idb
#	new file:   lab2/db/lab_general.cmp.logdb
#	new file:   lab2/db/lab_general.cmp.rdb
#	new file:   lab2/db/lab_general.cmp_merge.kpt
#	new file:   lab2/db/lab_general.cyclonev_io_sim_cache.ff_0c_fast.hsd
#	new file:   lab2/db/lab_general.cyclonev_io_sim_cache.ff_85c_fast.hsd
#	new file:   lab2/db/lab_general.cyclonev_io_sim_cache.ss_0c_slow.hsd
#	new file:   lab2/db/lab_general.cyclonev_io_sim_cache.ss_85c_slow.hsd
#	modified:   lab2/db/lab_general.db_info
#	new file:   lab2/db/lab_general.eda.qmsg
#	new file:   lab2/db/lab_general.fit.qmsg
#	new file:   lab2/db/lab_general.hier_info
#	new file:   lab2/db/lab_general.hif
#	new file:   lab2/db/lab_general.lpc.html
#	new file:   lab2/db/lab_general.lpc.rdb
#	new file:   lab2/db/lab_general.lpc.txt
#	new file:   lab2/db/lab_general.map.ammdb
#	new file:   lab2/db/lab_general.map.bpm
#	new file:   lab2/db/lab_general.map.cdb
#	new file:   lab2/db/lab_general.map.hdb
#	new file:   lab2/db/lab_general.map.kpt
#	new file:   lab2/db/lab_general.map.logdb
#	new file:   lab2/db/lab_general.map.qmsg
#	new file:   lab2/db/lab_general.map.rdb
#	new file:   lab2/db/lab_general.map_bb.cdb
#	new file:   lab2/db/lab_general.map_bb.hdb
#	new file:   lab2/db/lab_general.map_bb.logdb
#	new file:   lab2/db/lab_general.pre_map.cdb
#	new file:   lab2/db/lab_general.pre_map.hdb
#	new file:   lab2/db/lab_general.root_partition.map.reg_db.cdb
#	new file:   lab2/db/lab_general.routing.rdb
#	new file:   lab2/db/lab_general.rtlv.hdb
#	new file:   lab2/db/lab_general.rtlv_sg.cdb
#	new file:   lab2/db/lab_general.rtlv_sg_swap.cdb
#	new file:   lab2/db/lab_general.sld_design_entry_dsc.sci
#	new file:   lab2/db/lab_general.smart_action.txt
#	new file:   lab2/db/lab_general.sta.qmsg
#	new file:   lab2/db/lab_general.sta.rdb
#	new file:   lab2/db/lab_general.sta_cmp.8_H7_slow_1100mv_85c.tdb
#	new file:   lab2/db/lab_general.tis_db_list.ddb
#	new file:   lab2/db/lab_general.tiscmp.fast_1100mv_0c.ddb
#	new file:   lab2/db/lab_general.tiscmp.fast_1100mv_85c.ddb
#	new file:   lab2/db/lab_general.tiscmp.fastest_slow_1100mv_0c.ddb
#	new file:   lab2/db/lab_general.tiscmp.fastest_slow_1100mv_85c.ddb
#	new file:   lab2/db/lab_general.tiscmp.slow_1100mv_0c.ddb
#	new file:   lab2/db/lab_general.tiscmp.slow_1100mv_85c.ddb
#	new file:   lab2/db/lab_general.vpr.ammdb
#	new file:   lab2/db/lab_general_partition_pins.json
#	new file:   lab2/db/lpm_divide_2am.tdf
#	new file:   lab2/db/lpm_divide_52m.tdf
#	new file:   lab2/db/prev_cmp_lab_general.qmsg
#	new file:   lab2/db/sign_div_unsign_8kh.tdf
#	new file:   lab2/incremental_db/README
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.db_info
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.cmp.ammdb
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.cmp.cdb
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.cmp.dfp
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.cmp.hbdb.cdb
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.cmp.hbdb.hdb
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.cmp.hbdb.sig
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.cmp.hdb
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.cmp.logdb
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.cmp.rcfdb
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.map.cdb
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.map.dpi
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.map.hbdb.cdb
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.map.hbdb.hb_info
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.map.hbdb.hdb
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.map.hbdb.sig
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.map.hdb
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.root_partition.map.kpt
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.rrp.hdb
#	new file:   lab2/incremental_db/compiled_partitions/lab_general.rrs.cdb
#	new file:   lab2/lab_general.asm.rpt
#	new file:   lab2/lab_general.done
#	new file:   lab2/lab_general.eda.rpt
#	new file:   lab2/lab_general.fit.rpt
#	new file:   lab2/lab_general.fit.smsg
#	new file:   lab2/lab_general.fit.summary
#	new file:   lab2/lab_general.flow.rpt
#	new file:   lab2/lab_general.jdi
#	new file:   lab2/lab_general.map.rpt
#	new file:   lab2/lab_general.map.smsg
#	new file:   lab2/lab_general.map.summary
#	new file:   lab2/lab_general.pin
#	modified:   lab2/lab_general.qsf
#	modified:   lab2/lab_general.qws
#	new file:   lab2/lab_general.sld
#	new file:   lab2/lab_general.sof
#	new file:   lab2/lab_general.sta.rpt
#	new file:   lab2/lab_general.sta.summary
#	new file:   lab2/lab_general_nativelink_simulation.rpt
#	modified:   lab2/ram32x3.mif
#	new file:   lab2/runlab.do
#	new file:   lab2/simulation/modelsim/DE1_SoC_wave.do
#	new file:   lab2/simulation/modelsim/lab_general.sft
#	new file:   lab2/simulation/modelsim/lab_general.vo
#	new file:   lab2/simulation/modelsim/lab_general_modelsim.xrf
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do.bak
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do.bak1
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do.bak10
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do.bak11
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do.bak2
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do.bak3
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do.bak4
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do.bak5
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do.bak6
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do.bak7
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do.bak8
#	new file:   lab2/simulation/modelsim/lab_general_run_msim_rtl_verilog.do.bak9
#	new file:   lab2/simulation/modelsim/modelsim.ini
#	new file:   lab2/simulation/modelsim/msim_transcript
#	new file:   lab2/simulation/modelsim/ram32x3.mif
#	new file:   lab2/simulation/modelsim/ram32x3.ver
#	new file:   lab2/simulation/modelsim/rtl_work/_info
#	new file:   lab2/simulation/modelsim/rtl_work/_lib.qdb
#	new file:   lab2/simulation/modelsim/rtl_work/_lib1_0.qdb
#	new file:   lab2/simulation/modelsim/rtl_work/_lib1_0.qpg
#	new file:   lab2/simulation/modelsim/rtl_work/_lib1_0.qtl
#	new file:   lab2/simulation/modelsim/rtl_work/_vmake
#	new file:   lab2/simulation/modelsim/task2_wave.do
#	new file:   lab2/simulation/modelsim/task3_wave.do
#	new file:   lab2/simulation/modelsim/vsim.wlf
#	modified:   lab2/task2.sv
#	modified:   lab2/task3.sv
#	new file:   lab2/transcript
#	new file:   lab2/work/_info
#	new file:   lab2/work/_lib.qdb
#	new file:   lab2/work/_lib1_0.qdb
#	new file:   lab2/work/_lib1_0.qpg
#	new file:   lab2/work/_lib1_0.qtl
#	new file:   lab2/work/_vmake
#	new file:   work/_info
#
